language: php

php:
  - 7.2
  - 7.4

services:
  - mysql
  - postgresql

sudo: false

env:
  matrix:
    - DB=mysql DB_URL='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql DB_URL='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite DB_URL='sqlite:///:memory:'

  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - composer install --prefer-dist --no-interaction

  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:dev-next; fi

  - if [[ $PHPSTAN = 1 ]]; then composer require phpstan/phpstan-shim:^0.11; fi

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.2 ]]; then vendor/bin/phpunit; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.2 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan.phar analyse; fi

after_success:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.2 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
