language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
    - phpenv rehash

install:
    - composer self-update
    - composer install --dev
    - composer require cakephp/cakephp-codesniffer:dev-master

script:
  - phpunit
  - ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests

notifications:
  email: false
